import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Provider from "@/components/Provider";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider>
        <body
          className={`${inter.className} min-h-screen h-full flex flex-col`}
        >
          <Navbar />
          <main className="flex-1 w-full max-w-7xl mx-auto px-10">
            {children}
          </main>
          <Footer />
          <Toaster />
        </body>
      </Provider>
    </html>
  );
}
